### ISSUE TITLE
Review names

### ISSUE THREAD

**Issue by cxdemxn** [cxdemxn/techverse#5]
the names under each review needs to be changed because currently the names are anime character names.

**Comment by yekeen-nasir** [comment]
wow
alright
no problem

**Comment by cxdemxn** [comment]
captain k about to cook 👨‍🍳🫡

**Comment by yekeen-nasir** [comment]
guy....u just dey gimme work....wetin una dey do?

**Comment by yekeen-nasir** [comment]
what are we gon work on now?

**Comment by cxdemxn** [comment]
we'll have to work on interactivity. 
like the hamburger menu for mobile devices and the drop down thingy when a user clicks on frontend to see frontend related technology and what not
