### ISSUE TITLE
Review change

### ISSUE THREAD

**Issue by cxdemxn** [cxdemxn/techverse#6]
i suggest that the review themselves also change to make it seem more relatable??
or do you think they're fine as they are?? @yekeen-nasir

**Comment by yekeen-nasir** [comment]
let me check

**Comment by yekeen-nasir** [comment]
i think am done

**Comment by cxdemxn** [comment]
that's cool
you've merged it already?

**Comment by yekeen-nasir** [comment]
yh
surprisingly
it looks good actually
