### ISSUE TITLE
the service drop down

### ISSUE THREAD

**Issue by yekeen-nasir** [cxdemxn/techverse#9]
clicking on each service should result in a drop down menu showing the computer languages under it
i will actually love you to work on it
buh will u leave it to me?

**Comment by cxdemxn** [comment]
please, by all means do work on it
i don't know how to do such things yet

**Comment by yekeen-nasir** [comment]
ok.......i will need to open it with my desktop on github....so will do that today by God's grace

**Comment by yekeen-nasir** [comment]
ok...am done
tell me if i need to do more changes buh am leaving the icons to u bro

**Comment by yekeen-nasir** [comment]
yo, bari
whats up?
sorry....am fully back

**Comment by cxdemxn** [comment]
welcome back!

**Comment by yekeen-nasir** [comment]
so ....u done over here???
editing the remains?

**Comment by cxdemxn** [comment]
i've exported this webpage over to techverse's account under the repo name **_techverseWeb_**. 
i'll continue work from there

**Comment by yekeen-nasir** [comment]
alright bro
Good work
you can close this issue now
